[project]
name        = "veryl_testcase"
version     = "0.1.6"
authors     = ["dalance@gmail.com"]
description = "Testcases for test"
license     = "MIT"
repository  = "https://github.com/veryl-lang/veryl"

[build]
clock_type       = "posedge"
reset_type       = "async_low"
reset_low_suffix = "_n"
filelist_type    = "absolute"
sources          = ["testcases/veryl"]
target           = {type = "directory", path = "testcases/sv"}
sourcemap_target = {type = "directory", path = "testcases/map"}

[format]
indent_width = 4

[doc]
path = "target/veryl_doc"

[test]
simulator = "vcs"

[test.vcs]
compile_args = ["-full64"]

[dependencies]
veryl_sample  = {version = "0.13.0", github = "veryl-lang/sample"}
veryl_sample2 = {version = "0.14.0", project = "veryl_sample", github = "veryl-lang/sample"}
veryl_sample3 = {version = "0.15.0", project = "veryl_sample", git = "https://github.com/veryl-lang/sample"}
