[package]
name                  = "veryl-simulator"
version               = "0.16.3"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition.workspace     = true

[dependencies]
toml           = {workspace = true}
veryl-analyzer = {version = "0.16.3", path = "../analyzer"}
veryl-metadata = {version = "0.16.3", path = "../metadata"}
veryl-parser   = {version = "0.16.3", path = "../parser"}
veryl-path     = {version = "0.16.3", path = "../path"}
