name: Nightly Build

on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:

env:
  CHANNEL: -nightly

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Setup MUSL
      if: matrix.os == 'ubuntu-latest'
      run: |
        rustup target add x86_64-unknown-linux-musl
        sudo apt-get -qq install musl-tools
    - name: Setup aarch64 mac
      if: matrix.os == 'macOS-latest'
      run: |
        rustup target add aarch64-apple-darwin
        rustup target add x86_64-apple-darwin
    - name: Build for linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        make release_lnx
    - name: Build for macOS
      if: matrix.os == 'macOS-latest'
      run: make release_mac
    - name: Build for Windows
      if: matrix.os == 'windows-latest'
      run: make release_win

    - name: Release for linux
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: x86_64-linux
        path: '*-x86_64-linux.zip'

    - name: Release for macOS (x86_64)
      if: matrix.os == 'macOS-latest'
      uses: actions/upload-artifact@v4
      with:
        name: x86_64-mac
        path: '*-x86_64-mac.zip'

    - name: Release for macOS (aarch64)
      if: matrix.os == 'macOS-latest'
      uses: actions/upload-artifact@v4
      with:
        name: aarch64-mac
        path: '*-aarch64-mac.zip'

    - name: Release for Windows
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: x86_64-windows
        path: '*-x86_64-windows.zip'
